# Generated by Django 3.1 on 2020-09-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200829_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_user',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
