# Generated by Django 3.1 on 2020-09-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200902_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image_user',
        ),
    ]
