# Generated by Django 3.1 on 2020-09-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='image_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='placeholder-1.jpg', upload_to='profile_photo/', verbose_name='profile photo'),
        ),
    ]
