# Generated by Django 3.0.8 on 2020-08-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='img_url',
            field=models.CharField(default='https://api.time.com/wp-content/uploads/2019/03/us-movie-rabbits-meaning.jpg?w=800&quality=85', max_length=200),
        ),
    ]
