# Generated by Django 3.0.8 on 2020-08-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsstory_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='img_url',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='image_url',
            field=models.CharField(default='https://api.time.com/wp-content/uploads/2019/03/us-movie-rabbits-meaning.jpg', max_length=200),
        ),
    ]
