# Generated by Django 3.0.8 on 2020-08-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200822_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='story_img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
