# Generated by Django 3.0.8 on 2020-08-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200825_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category_story',
            field=models.CharField(default='Brisbane-Events', max_length=200),
        ),
    ]
