# Generated by Django 3.1 on 2020-09-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsstory_category_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='main_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
