# Generated by Django 3.1 on 2020-09-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newsstory_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='main_image',
        ),
    ]
